# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  lavidb-app:
    image: lavidb
    restart: always
    ports:
      - 0.0.0.0:443:443
